# Generated by Django 4.1.4 on 2023-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('english', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('economics', models.IntegerField()),
                ('history', models.IntegerField()),
                ('civics', models.IntegerField()),
            ],
        ),
    ]
